apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: dart-heroes
spec:
  type: LoadBalancer
  selector:
    app: dart-heroes
    role: Frontend
  ports:
    - port: 80
      targetPort: 8080